version: "3"

volumes:
  esdata01:
    driver: local


networks:
  backend:
  frontend:
    driver: bridge # use the bridge driver
    ipam:
      driver: default

services:
  bootstrap:
    hostname: bootstrap
    container_name: bootstrap01
    image: enigmampc/worker_sw:latest
    depends_on:
      - contract
      - km
    environment:
      ENIGMA_ENV: COMPOSE
      SGX_MODE: SW
      BOOTSTRAP: "TRUE"
      MIN_CONFIRMATION: 1
    expose:
      - "10300" # libp2p port
      - "8080"  # what is this?
    ports:
      - "3346:3346"
      - "9229:9229"

  worker:
    hostname: worker
    image: enigmampc/worker_sw:latest
    depends_on:
      - contract
      - km
    environment:
      ENIGMA_ENV: COMPOSE
      SGX_MODE: SW
      MIN_CONFIRMATION: 1
      # FORCE_NEW_ETH_ADDR: "true"
    expose:
      - "8080" # what is this?
      - "9229"
      - "3346"
      - "10300" # libp2p

  contract:
    hostname: contract
    container_name: contract
    image: enigmampc/contract:latest
    environment:
      SGX_MODE: SW
      ENIGMA_ENV: COMPOSE
      AUTO_MINER: "ON"
      BLOCK_TIME: 0
      TIME_BETWEEN_BLOCKS: 5
    ports:
      - "8081:8081" # contract discovery service
      - "9545:9545" # ethereum node port
      - "8001:8001" # faucet port

  km:
    hostname: km
    container_name: km
    image: enigmampc/key_management_sw:latest
    environment:
      ENIGMA_ENV: COMPOSE
      SGX_MODE: SW
      CONFIRMATIONS: 1
    expose:
      - "3040" # JSON RPC port
      - "8081"

#  client:
#    hostname: client
#    image: enigmampc/client:latest
#    stdin_open: true
#    tty: true
#    depends_on:
#      - contract
#    environment:
#      ENIGMA_ENV: COMPOSE
#      SGX_MODE: SW
